CREATE TABLE IF NOT EXISTS board (
    id INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    author_id INTEGER NOT NULL,
    board_name TEXT NOT NULL CHECK (LENGTH(board_name) <= 128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_private BOOLEAN NOT NULL DEFAULT FALSE,
    flow_count INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (author_id) REFERENCES flow_user(id) ON DELETE CASCADE,
    UNIQUE (author_id, board_name)
);