CREATE TABLE message (
    id INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    content TEXT NOT NULL,
    sender TEXT NOT NULL,
    recipient TEXT NOT NULL,
    chat_id INT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    is_read BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_chat FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE
);
