version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - internal/grpc
    - protos
  skip-files:
    - ".*_test.go"
    - ".*/mock_.*.go"

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - ineffassign
