services:
  backend:
    container_name: flow_backend
    build: .
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - IP=${IP}
      - ENVIRONMENT=${ENVIRONMENT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "${PORT}:${PORT}"
