services:
  database:
    networks:
      - flow_network
    container_name: postgres_db
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    networks:
      - flow_network
    container_name: flow_backend
    build: 
      context: .
      dockerfile: app/main/Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - IP=${IP}
      - ENVIRONMENT=${ENVIRONMENT}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PORT=${PORT}
      - EXPIRATION_TIME=${EXPIRATION_TIME}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - VK_CLIENT_ID=${VK_CLIENT_ID}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    volumes:
      - ./static:/app/static

  auth:
    networks:
      - flow_network
    container_name: auth
    build:
      context: .
      dockerfile: app/auth/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "8010:8010"
    depends_on:
      - database
    
  feed:
    networks:
      - flow_network
    container_name: feed
    build:
      context: .
      dockerfile: app/feed/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "8011:8011"
    depends_on:
      - database
  
  prometheus:
    networks:
      - flow_network
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  node_exporter:
    networks:
      - flow_network
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    hostname: node_exporter
    ports:
      - "9100:9100"
    depends_on:
      - prometheus
  
  grafana:
    networks:
      - flow_network
    image: grafana/grafana-enterprise
    volumes:
      - ${GRAFANA_DIR}:/var/lib/grafana/
      - ${GRAFANA_DIR}/provisioning/:/etc/grafana/provisioning/
      - ${GRAFANA_DIR}/dashboards:/etc/grafana/dashboards
    user: "${UID}"
    ports:
      - "9010:3000"
    depends_on:
      - prometheus

networks:
  flow_network:
    driver: bridge

volumes:
  db_data:
