REASSIGN OWNED BY :role_name TO admin;
DROP OWNED BY :role_name;
DROP ROLE IF EXISTS :role_name;

CREATE ROLE :role_name WITH 
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	NOBYPASSRLS
	LOGIN
	PASSWORD :role_password
	CONNECTION LIMIT -1;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO :role_name;