global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'localhost:9090' ]
      
  - job_name: "node_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node_exporter:9100' ]
  
  - job_name: "flow_backend"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ 'flow_backend:8080' ]

  - job_name: "auth"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ 'auth:2112' ]
  
  - job_name: "feed"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ 'feed:2112' ]