{
 "title": "flow_backend",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Hits per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, path) (rate(http_method_hits_total[1m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Errors per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, path, description) (rate(http_method_errors_total[1m]))",
     "legendFormat": "{{method}} {{path}} : {{description}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (rate(http_method_duration_seconds_bucket[1m])))",
     "legendFormat": "{{method}} {{service}}"
    }
   ]
  }
 ]
}