CREATE TABLE IF NOT EXISTS poll(
	id INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	name TEXT CHECK (LENGTH(name) <= 127),
	screen TEXT,
	delay INT DEFAULT 0,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);