// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1576e6ecDecodeGithubComGoParkMailRu20251SuperChipsDomain(in *jlexer.Lexer, out *RequestBodyFlowID) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "flow_id":
			if in.IsNull() {
				in.Skip()
				out.FlowID = nil
			} else {
				if out.FlowID == nil {
					out.FlowID = new(int)
				}
				*out.FlowID = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1576e6ecEncodeGithubComGoParkMailRu20251SuperChipsDomain(out *jwriter.Writer, in RequestBodyFlowID) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"flow_id\":"
		out.RawString(prefix[1:])
		if in.FlowID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.FlowID))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestBodyFlowID) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1576e6ecEncodeGithubComGoParkMailRu20251SuperChipsDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestBodyFlowID) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1576e6ecEncodeGithubComGoParkMailRu20251SuperChipsDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestBodyFlowID) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1576e6ecDecodeGithubComGoParkMailRu20251SuperChipsDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestBodyFlowID) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1576e6ecDecodeGithubComGoParkMailRu20251SuperChipsDomain(l, v)
}
