name: test, lint and deploy

on:
  push:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: go setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: install dependencies
        run: go mod download && go install go.uber.org/mock/mockgen@latest
      
      - name: install linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

          golangci-lint --version

      - name: tests
        run: |
          make mocks
          make test
      
      - name: run linter
        run: golangci-lint run --timeout=5m --verbose
      
  deploy:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: restart containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/superchips/2025_1_SuperChips
            sudo git switch main
            sudo git pull
            
            sudo docker compose --env-file variables.env build
            sudo docker compose --env-file variables.env up -d --remove-orphans

    